version = 1

# ① 兜底(必须放最前;后匹配者优先)。本仓 SPDX = MIT(CLI 是 MIT 单许可仓,12 §1.3)。
[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2026 Synchain"
SPDX-License-Identifier = "MIT"

# ② 生成物特例(覆盖兜底,同 SPDX;显式登记为生成物,不逐文件加头)
[[annotations]]
path = ["package-lock.json", "dist/**"]
SPDX-FileCopyrightText = "2026 Synchain"
SPDX-License-Identifier = "MIT"
